behaviors:
  PommermanBot:
    trainer_type: ppo
    
    # 2. Ustawienia specyficzne dla trenera PPO
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
    
    # 3. Ustawienia Generalne
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 15000
    
    # 4. Ustawienia Sieci
    network_settings:
      # normalize: true
      hidden_units: 128
      num_layers: 2
      
    # 5. Ustawienia Nagrod
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    
    # 6. Ustawienia Treningu
    threaded: True


# behaviors:
#   # Nazwa musi byc IDEALNIE taka sama jak Behavior Name w Unity
#   PommermanBot:
#     # 1. Okreslamy typ trenera
#     trainer_type: ppo
#     init_path:  results/Pommerman_New_IL2_2ndIL_Inference2_NewObs/PommermanBot/PommermanBot-4822454.pt
#     # 2. Ustawienia specyficzne dla trenera PPO
#     hyperparameters:
#       batch_size: 2048
#       buffer_size: 20480
#       learning_rate: 2.0e-4
#       beta: 5.0e-3
#       epsilon: 0.15
#       lambd: 0.95
#       num_epoch: 5
#     # 3. Ustawienia Generalne
#     max_steps: 10000000
#     time_horizon: 256
#     summary_freq: 5000
    
#     # 4. Ustawienia Sieci
#     network_settings:
#       # normalize: true
#       hidden_units: 128
#       num_layers: 2
      
#     # 5. Ustawienia Nagrod
#     reward_signals:
#       extrinsic:
#         gamma: 0.999
#         strength: 1.0
    
#     # self_play:
#     #   save_steps: 50000        
#     #   team_change: 200000      
#     #   swap_steps: 5000         
#     #   window: 10               
#     #   play_against_latest_model_ratio: 0.5
    
#     # behavioral_cloning:
#     #   demo_path: Demonstrations/PommermanDemo_10.demo
#     #   strength: 0.6
#     #   steps: 150000
#     # 6. Ustawienia Treningu
#     threaded: True
   
#     # init_path: None