behaviors:
  # Nazwa musi byc IDEALNIE taka sama jak Behavior Name w Unity
  PommermanBot:
    # 1. Okreslamy typ trenera
    trainer_type: ppo

    # 2. Ustawienia specyficzne dla trenera PPO
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # 3. Ustawienia Generalne
    max_steps: 100000
    time_horizon: 256
    summary_freq: 10000

    # 4. Ustawienia Sieci
    network_settings:
      hidden_units: 128
      num_layers: 2

    # 5. Ustawienia Nagrod
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    # 6. Ustawienia Treningu
    threaded: True
    # init_path: None
